server:
  port: 8189
  servlet:
    context-path: /users

spring:
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: Evengarr
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
